### ISSUE TITLE
Move Button from TinyMCE over to Add Media 

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/mediacore-wordpress#2]
I've made a plea over on the Shortcake repo for more standardization on how media is added to a post: https://github.com/fusioneng/Shortcake/issues/281#issuecomment-107759742

I think the Add Media space is the best space for this to happen. Given that the Mediacore Plugin currently creates an Shortcode, perhaps integration with the Shortcake functionality is the best way forward. Whether it's a separate link, or an option within the Add Media Element menu added by Shortcake, I think moving the Mediacore button over to Add Media would make for a better user experience (the small orange icon on the toolbar is not the most easily found item).

![2015-07-06_16-24-36](https://cloud.githubusercontent.com/assets/480667/8532549/e9ea9a5c-23fc-11e5-95a8-6301d5059d04.jpg)

I've made this suggestion over on the mediacore repo, in this issue https://github.com/mediacore/mediacore-wordpress/issues/3 I think it's something worth developing out.

**Comment by mrjarbenne** [comment]
The easiest way to do this would be to add Shortcake support to the existing plugin, rather than adding an additional navigation element to the Media Explorer Nav.

**Comment by mrjarbenne** [comment]
This is very similar to the GDrive Media Explorer functionality. Perhaps we can use a similar strategy. The limitations in the Shortcake Attributes screen make it incompatible with this idea. The Mediacore Chooser will need to be loaded in the backbone window as seen in the screenshot above.

**Comment by r-a-y** [comment]
I haven't looked into how Mediacore works, but if Mediacore already uses some form of frame to display their contents, moving that to Backbone is a no-go.

If we just want to move their functionality into the "Add Media" modal, that might be easier to do.

Let me know where this fits in priority-wise.

**Comment by mrjarbenne** [comment]
Here's a brief walkthrough of what Mediacore does. The LMS/D2L integration leverages a new Trusted Embeds API that automatically adds an authorization token so that videos that otherwise are private based on permissions set on the mediacore website, can be made available wherever they are placed. 

In an LMS, the private videos, when placed in a course -- through the power of this additional token (similar to the powers of greyskull -- can be viewed by anyone with permission to access the course. 

In WordPress, inserting a video should make the video public, allowing anyone with access to the site, to be able to access the video.

http://www.screencast.com/t/3MUBvAOelUIo

The documentation for trusted embeds can be found in issue #1

**Comment by mrjarbenne** [comment]
Disregard.
